version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "3333:3333"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: films
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
